### ISSUE TITLE
allow string delineation for use with a list in a params file

### ISSUE THREAD

**Issue by lrstanley** [pivotal-cf/email-resource#30]
Right now, you can only specify an array with the `To` parameter, or a file. You could make a variable, and use it within that array, however you can then only specify one URL from my testing.

What would be useful, is for each item in the array, try and split it by comma delineation (much like having it be in a file), or support a string rather than an array, and do comma delineation there (I'm not sure if this is a limitation on `email-resource`, or concourse).

I.e:

```
  name: send-mail
  type: email
  source:
    from: ((email-notify-address))
    smtp:
      host: smtp.domain.com
      password: ((email-notify-password))
      port: "25"
      skip_ssl_validation: true
      username: ((email-notify-username))
   to: "user1@domain.com,user2@domain.com"
# parameterized would be:
#    to: [ ((email-list-variable)) ]
```

This way, `user1@domain.com,user2@domain.com` as a string can be hoisted out into concourse param files.

Or:
```
  name: send-mail
  type: email
  source:
    from: ((email-notify-address))
    smtp:
      host: smtp.domain.com
      password: ((email-notify-password))
      port: "25"
      skip_ssl_validation: true
      username: ((email-notify-username))
   to: [ "user1@domain.com,user2@domain.com", "user3@domain.com,user4@domain.com" ]
# parameterized would be:
#    to:
#      - ((email-list-developers))
#      - ((email-list-po))
```

Where we can specify two different lists in the params files (e.g. `email-high-priority`, `email-high-priority`, or maybe `email-fail-list`, `email-success-list`), etc.

**Comment by calebwashburn** [comment]
You should be able to do this natively with concourse by changing the pipeline to accept an entire array vs enclosed in an array.  See example of removing variable enclosed in array '[ ]' 

```
resources:
- name: send-an-email
  type: email
  source:
    smtp:
      host: {{smtp-host}}
      port: {{smtp-port}}
      username: {{smtp-username}}
      password: {{smtp-password}}
    from: {{email-from}}
    to: {{email-to-array}}
```

Then in your params file you can specify the variable as such:

```
email-to-array: ["test@test.com", "test2@test.com"]
```
