### ISSUE TITLE
[Feature] Make metadata available in body property

### ISSUE THREAD

**Issue by klhex** [pivotal-cf/email-resource#43]
Current documentation says: "You can use the values below in any of the source files or text properties to access the corresponding metadata made available by concourse".

It would be nice if the concourse metadata (such as $BUILD_JOB_NAME) was also made available in the "body" property, to be used like this, for example:

```yaml
    on_success:
      try:
        put: email
        params:
          subject_text: "${BUILD_JOB_NAME} (${BUILD_NAME})"
          body: uploads/${BUILD_JOB_NAME}.log
```

Currently, no variable expansion takes place within the body property.
