### ISSUE TITLE
Issue with attachment_globs field

### ISSUE THREAD

**Issue by Akshaya-Shankar** [pivotal-cf/email-resource#44]
I'd like to send an email with a file attached from concourse pipeline and I faced below error.
_Error during execute - unmarshalling input: json: cannot unmarshal string into Go struct field Params.params.attachment_globs of type []string_

I tried below pipeline.
```
    on_failure:
      do:
        - put: send-an-email
          params:
            subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}"
            body_text: "Build failed: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
            attachment_globs: repository/close_file_attach.txt
```

Please help me out with this.
